spring.application.name=om-backend
server.port=8080

# ? PostgreSQL Connection Settings
spring.datasource.url=jdbc:postgresql://localhost:5432/om_medical
spring.datasource.username=postgres
spring.datasource.password=2026
spring.datasource.driver-class-name=org.postgresql.Driver

# ?? JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

app.jwt.secret=SudiptoKARMAKARisanotgoodbyandHeisveryaerogentandAlsolovinG
app.jwt.expiration=86400000